config:
    platform: Windows # also can be windows, Linux, Mac. Will support Windows first

log:
    format: # define the format of logging utility

Mac:  # the command used in project
    browser: Chrome
    whether_running: pgrep
    file_name: /tmp/novel.txt

Windows:
    browser: chrome
    whether_running: tasklist | grep

Linux:
    browser: Chrome
    whether_running: pgrep
    file_name: /tmp/novel.txt


